### ISSUE TITLE
Authentication token should be per datasource

### ISSUE THREAD

**Issue by rledisez** [CityzenDataOSS/grafana-warp#8]
The token used to authenticate against warp endpoint should be defined at the datasource level to avoid writing it in every warpscript. Because, if the token change, it would be very annoying to edit the tens/hundreds of scripts just to update the token.

The datasource should replace a well defined string in the warp script by the token.

Eg:

WARP script:
[ $warp_ds_token '=my.timeserie' { 'tag' 1 } $end $interval ] FETCH 'gts' STORE

The datasource would replace $warp_ds_token by the token.

It seems easy to do in datasource.js, function metricFindQuery().

**Comment by StevenLeRoux** [comment]
The project has moved under : https://github.com/cityzendata/grafana-warp10

Could you write your issue there ?

thx

**Comment by rledisez** [comment]
Moved: https://github.com/cityzendata/grafana-warp10/issues/12
